config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "beans#index"

  resources :beans

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bean.rb
class Bean < ApplicationRecord
  belongs_to :country 
end

app/models/country.rb
class Country < ApplicationRecord
  has_many :beans
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/beans_controller.rb
class BeansController < ApplicationController

  def index
    @beans = Bean.all #- we do need this, if we go with my new idea. We want it to display all the beans that we have, but just display the roast. we probably do not need this as we dont want to see all the beans anyway
  end

  def show
    @bean = Bean.find(params[:id])
  end

  def new
    @bean = Bean.new
  end

  def create

    bean_params = params.require( :bean ).
      permit( :name, :roast, :flavour, :price, :image_url, :description, :country_id )

    @bean = Bean.new(bean_params)
    if @bean.save
      redirect_to @bean
    else
      render 'new'
    end
  end

    def edit
      @bean = Bean.find(params[:id])
    end

    def update
      bean_params = params.require( :bean ).permit( :name, :roast, :flavour, :price, :image_url, :description, :country_id )

      @bean = Bean.find(params[:id])
      if @bean.update_attributes( bean_params )
        redirect_to @bean
      else
        render 'edit'
      end
    end #of method update

    def destroy
      @bean = Bean.find(params[:id])
      @bean.destroy
      redirect_to beans_path
    end #of method destroy

end #end of class

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/beans_helper.rb
module BeansHelper
end

app/views/beans/_form.html.erb
<head>
  <link href="https://fonts.googleapis.com/css?family=Noto+Sans" rel="stylesheet">
</head>



  <%= form_for @bean do |f| %>
    <div><%= f.label :name, class: "name_label"%>
    <%= f.text_field :name, class: "text_field"%></div>

    <div><%= f.label :roast, class: "name_label"%>
    <%= f.text_field :roast, class: "text_field" %></div>

    <div><%= f.label :flavour, class: "name_label"%>
    <%= f.text_field :flavour, class: "text_field"%></div>

    <div><%= f.label :price, class: "name_label"%>
    <%= f.number_field :price, class: "text_field" %></div>

    <div><%= f.label :description, class: "name_label"%>
    <%= f.text_field :description, class: "text_field" %></div>

    <div><%= f.label :image_url, class: "name_label"%>
    <%= f.text_field :image_url, class: "text_field"%></div>

    <div><%= f.label :country_id, class: "name_label"%>
    <%= f.collection_select(:country_id, Country.all, :id, :name) %></div>

    <div class="create_button"><%= f.submit (@bean.new_record? ? "Create" : "Update") %></div>

  <% end %>

app/views/beans/edit.html.erb
<h2> EDIT BEAN </h2>

  <%= render "form" %>

app/views/beans/index.html.erb
<head>
  <link rel="stylesheet" href="beans.scss">
</head>

<body class="index_body">



<div class="banner">
  <img class="banner-logo" src="https://www.feedprojects.com/sites/default/files/blogs/Banner_D_5.jpg">
  <h2 class="page-title">ALL BEANS</h2>
</div>

<main class="product-main">

  <% @beans.each do |bean| %>
    <article class="product-card">
      <%= image_tag bean.image_url, class: "product-card-image" %>
      <%= link_to bean.name, bean_path(bean.id), class: "product-card-name" %>
    </article>
  <% end %>
</main>


    <div class="new-button">
      <%= link_to "NEW", new_bean_path, class:"new-button" %>
    </div>



</body>

app/views/beans/new.html.erb
<head>
  <link href="https://fonts.googleapis.com/css?family=Noto+Sans" rel="stylesheet">
</head>

<h2> NEW BEAN </h2>

  <%= render "form" %>

app/views/beans/show.html.erb
<head>
  <link href="https://fonts.googleapis.com/css?family=Noto+Sans" rel="stylesheet">
</head>

<h2><%= @bean.name %></h2>

  <div class="descr">Roast</div>
  <div class="thing"><%= @bean.roast.capitalize %></div>

  <div class="descr">Flavour</div>
  <div class="thing"><%= @bean.flavour.capitalize %></div>

  <div class="descr">Country</div>
  <div class="thing"><%= @bean.country.name %></div>

  <div class="descr">Price</div>
  <div class="thing">€ <%= @bean.price %></div>

  <div><%= image_tag @bean.image_url%></div>


  <div class="buttons"><%= link_to "EDIT", edit_bean_path(@bean.id), class: "edit_button"%>
  <%= link_to "DELETE", bean_path(@bean.id), method: :delete, data: {confirm: "Are you sure?"}, class: "delete_button" %></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OneTooMany</title>

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Bungee+Inline%7CBungee+Outline%7CChanga%7CCutive+Mono%7CFascinate%7CGeostar+Fill%7CJulius+Sans+One%7CLalezar%7CMegrim%7CMonofett%7CMonoton%7CPlaster%7CPress+Start+2P%7CRationale%7CShare+Tech+Mono" rel="stylesheet"
    <link rel="stylesheet" href="normalize.css">
  </head>

  <header class="header">
    <h1 class="main-title"> ONE_TOO_MANY? </h1>
    <p> TRUE: because there can never be too many beans. </p>
  </header>

  <body>

    <%= yield %>

    <footer class="footer">
        2016 one_too_many?
    </footer>
  </body>



</html>